server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://jobportal-db:3306/jobportal_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${AUTH_SERVICE_DB_USERNAME:root}
    password: ${AUTH_SERVICE_DB_PASSWORD:billa}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${AUTH_SERVICE_JWT_SECRET}
  access-expiry-ms: ${AUTH_SERVICE_JWT_ACCESS_EXPIRY}
  refresh-expiry-ms: ${AUTH_SERVICE_JWT_REFRESH_EXPIRY}

cloudinary:
  cloud-name: ${AUTH_SERVICE_CLOUDINARY_CLOUD_NAME}
  api-key: ${AUTH_SERVICE_CLOUDINARY_API_KEY}
  api-secret: ${AUTH_SERVICE_CLOUDINARY_API_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, info