#spring.application.name=JPMS-JobService
server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.exchange=jobportal.exchange
rabbitmq.queue=job.posted.queue
rabbitmq.routing-key=job.posted

# Zipkin config
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Logging pattern (ADD THIS)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]