server.port=9091
spring.application.name=CUSTOMER-SERVICE

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:billa}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# When running locally -uses localhost:9090
# When running in Docker - Docker Compose overrides with login-service:9090
login.service.url=${LOGIN_SERVICE_URL:http://localhost:9090}